### ISSUE TITLE
[ERR_MODULE_NOT_FOUND] when loading from an ESM project

### ISSUE THREAD

**Issue by ritschwumm** [ldapts/ldapts#144]
i use ldapts in a fully ESM project. 

after upgrading from 6.0.0 to 7.0.1 i get a runtime error from node.js

`[ERR_MODULE_NOT_FOUND]: Cannot find module '/node_modules/ldapts/Attribute' imported from /node_modules/ldapts/messages/AddRequest.js`

interestingly, the import in `messages/AddRequest.js`  is missing the file extension which probably explains the problem.

i  patched this and a few other imports lacking a file extension, and got a bit further. now running my code fails with

```
file:///app/node_modules/ldapts/controls/EntryChangeNotificationControl.js:1
import { BerWriter } from 'asn1';
         ^^^^^^^^^
SyntaxError: The requested module 'asn1' does not provide an export named 'BerWriter'
```

this might be some misconfiguration on my side, but all other libraries i use work just fine...

**Comment by jgeurts** [comment]
Thank you for letting me know! I apologize for the troubles with the 7.x version. Could you please try 7.0.2 when you have a chance? It should have all of the file extension issues fixed and _hopefully_ fixes the asn1 imports.

**Comment by ritschwumm** [comment]
digging deeper i cannot find anything that would prevent this import from working. 

but: https://nodejs.org/api/esm.html#interoperability-with-commonjs says 
`When importing CommonJS modules(https://nodejs.org/api/esm.html#commonjs-namespaces), the module.exports object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.`
and i'm not sure what "may be available" means exactly. could it be the mentioned "static analysis" is failing for asn1?

**Comment by ritschwumm** [comment]
according to https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/ the "static analysis"  is not something you can rely on in all cases - even if https://github.com/nodejs/node/blob/main/deps/cjs-module-lexer/README.md at least at first glance looks like it should recognize the exports in asn1.

anyway, i think i have found a workaround:

this code which failes and does rely on the "static analysis" (see https://github.com/nodejs/node/blob/main/deps/cjs-module-lexer/README.md)
```javascript
import { BerWriter } from 'asn1';
```

can be replaced with this alternative code which does _not_ rely on the static analysis and works:
```javascript
import asn1 from 'asn1';
const { BerWriter } = asn1;
```

when i patch the javascript code of ldapts like this in `node_modules` , my app starts just fine.

maybe it's a better solution to change asn1 in a way which makes node's esm module loader happy instead, but as a workaround this seems to be fine.

**Comment by jgeurts** [comment]
Thanks for working through this with me! Could you please try 7.0.3 when you get a chance?

**Comment by ritschwumm** [comment]
just checked, 7.0.3 works like a charm. thank you very much for resolving this so quickly - and for moving ldapts to ESM even if it's a bit of a hassle.

**Comment by jgeurts** [comment]
@ritschwumm Would you be able to check `v7.0.5-beta1`? I ran into an issue on the CommonJS side of things and changed up how the npm package was bundled. Caveat that all exports are moved to the root namespace now. So, for example, `import { Control } from 'ldapts/controls';` would change to `import { Control } from 'ldapts';`

**Comment by ritschwumm** [comment]
@jgeurts works for me, both at compile- and at runtime.
our usecase it pretty simple though, the only thing i ever actively use is `import { Client } from "ldapts";`

**Comment by jgeurts** [comment]
Great, thanks for checking!
